language: python
python: 2.7
os:
  - linux
#  - osx
env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
matrix:
  fast_finish: true
  include:
    - python: 3.5
      env:
      - TOXENV=py35
  allow_failures:
    - os: osx
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success: coveralls
