language: python
python: 2.7
os:
  - linux
  - osx
env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=jython
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
